/**
 * Demo profiles (TODO-backend.md §9).
 *
 * They are **generated by running the engine**, never hand-written. A profile
 * typed by hand drifts: the history says one thing, the counters another, and
 * the first person to check the arithmetic on stage finds it. Simulating day by
 * day means the state is consistent by construction — and it exercises the same
 * code path the real app uses.
 *
 * The recovery days in `avanzato` are not sprinkled in for looks: they are the
 * rest days and the revaluation visit that the plan itself prescribes. That is
 * the "senza barare" story, visible in the calendar.
 */

import { avanzaFase, chiudiGiornata, faseCorrente, nuovoGiorno } from '../../domain/scoring.js';
import { VERSIONE_STATO } from '../../domain/costanti.js';
import { aggiungiGiorni, giornataLogica } from '../../domain/tempo.js';
import type { DataISO, DatiPersistiti, StatoUtente } from '../../domain/types.js';
import { creaPianoMarco } from './piano-marco.js';

export type NomeProfilo = 'nuovo' | 'avanzato' | 'soglia' | 'vetrina' | 'settimana' | 'presentazione';

export const PROFILI: Record<NomeProfilo, string> = {
  nuovo: 'Primo accesso: giorno 1, tutto a zero',
  avanzato: 'Giorno 40, streak lungo, calendario e grafico pieni',
  soglia: 'A una giornata dal level-up, per far accadere il momento clou a comando',
  vetrina: 'Fase 3 raggiunta: entrambi i benefit sbloccati, streak lungo, per presentazioni',
  settimana: 'Giorno 8, i primi 7 giorni pieni: stessi numeri del fixture, ma con storico vero',
  presentazione: 'A una giornata dal level-up in fase 3: per mostrare lo sblocco del calendario dal vivo',
};

/** What the user did on a simulated day. */
type Comportamento = 'pieno' | 'parziale' | 'saltato';

const STATO_ZERO: Omit<StatoUtente, 'sogliaFaseAttuale'> = {
  faseRaggiunta: 1,
  rpProgressoFase: 0,
  rpTotali: 0,
  giorniFaseTrascorsi: 0,
  gemmePortafoglio: 0,
  streakGiorni: 0,
  moltiplicatoreAttuale: 1,
  recuperiManualiUsatiInFase: 0,
  giorniVasAltiConsecutivi: 0,
  avanzamentoDisponibile: false,
  ultimaGiornataChiusa: null,
};

/** A clean slate whose plan starts on `dataInizio`. */
function vuoto(dataInizio: DataISO): DatiPersistiti {
  const piano = creaPianoMarco(dataInizio);
  const fase1 = piano.fasi[0];
  if (!fase1) throw new Error('piano senza fasi');
  return {
    versione: VERSIONE_STATO,
    piano,
    stato: { ...STATO_ZERO, sogliaFaseAttuale: fase1.sogliaRp },
    giornoCorrente: nuovoGiorno(dataInizio),
    storico: [],
    voucher: [],
  };
}

/** Fills today's checklist according to `come`, then closes the day. */
function simulaGiorno(dati: DatiPersistiti, come: Comportamento, vas: number): DatiPersistiti {
  const fase = faseCorrente(dati);
  const esercizi = fase.esercizi.map((e) => e.id);
  const dosi = fase.farmaci.flatMap((f) => f.orario.map((o) => `${f.id}@${o}`));

  const giornoCorrente = {
    ...dati.giornoCorrente,
    eserciziFatti: come === 'pieno' ? esercizi : come === 'parziale' ? esercizi.slice(0, 1) : [],
    dosiPrese: come === 'saltato' ? [] : dosi,
    diario: come === 'saltato' ? null : { vas, compilatoAlle: '20:30' },
  };

  const chiuso = chiudiGiornata({ ...dati, giornoCorrente });
  // The demo auto-confirms the level-up, so the moment is visible without a
  // physio in the room.
  return chiuso.stato.avanzamentoDisponibile ? avanzaFase(chiuso) : chiuso;
}

/**
 * Simulates `giorni` days ending yesterday, so the profile leaves today open
 * and the demo starts on a fresh checklist.
 */
function simula(
  giorni: number,
  comportamento: (indice: number) => Comportamento,
  dolore: (indice: number) => number,
  adesso: Date,
): DatiPersistiti {
  const oggi = giornataLogica(adesso);
  let dati = vuoto(aggiungiGiorni(oggi, -giorni));
  for (let i = 0; i < giorni; i++) {
    dati = simulaGiorno(dati, comportamento(i), dolore(i));
  }
  return dati;
}

/** Pain that wanders instead of sitting still: the chart needs a shape. */
function doloreRealistico(indice: number): number {
  const onda = [5, 4, 4, 6, 3, 4, 5, 3, 2, 4, 3, 2, 3, 2];
  return onda[indice % onda.length] ?? 3;
}

export function creaProfilo(nome: NomeProfilo, adesso: Date = new Date()): DatiPersistiti {
  switch (nome) {
    case 'nuovo':
      return vuoto(giornataLogica(adesso));

    /**
     * Forty-one days of history. Day one is deliberately incomplete — the
     * calendar needs a lost day to be worth looking at — and everything after
     * it is full. The six recovery days come from the plan (rest days and the
     * two revaluation visits), so the streak survives them: 34 full days, x2.65.
     *
     * The count is 41 and not 40 for a reason worth keeping: at 40 the day left
     * open is the revaluation at offset 41, so the profile loaded straight into
     * a frozen checklist and there was nothing to tick on stage.
     */
    case 'avanzato':
      return simula(41, (i) => (i === 0 ? 'parziale' : 'pieno'), doloreRealistico, adesso);

    /**
     * Fourteen days in phase one, one of which is a prescribed rest day: 13
     * full days, 286 of 308 RP. Exactly one more full day closes the phase, so
     * the level-up happens when the presenter wants it and not before.
     */
    case 'soglia':
      return simula(14, () => 'pieno', doloreRealistico, adesso);

    /**
     * Fifty days, day one incomplete for the same reason as `avanzato`. Crosses
     * both phase boundaries (day 42 closes phase 2) and lands eight days into
     * phase 3: 42 full days, x3.05, both in-app benefits unlocked
     * (`grafico-dolore` at phase >= 2, `calendario-heatmap` at phase >= 3) —
     * for demos that need to show those two screens without narrating a
     * level-up first.
     */
    case 'vetrina':
      return simula(50, (i) => (i === 0 ? 'parziale' : 'pieno'), doloreRealistico, adesso);

    /**
     * Seven full days, all in phase one. Reproduces `fixture.ts`'s numbers
     * exactly — 154 RP, 177.1 gems, streak 7, x1.30 — because `simula` runs
     * the same day-close math the fixture's numbers were hand-copied from.
     * Unlike the fixture, `storico` actually gets the seven entries, so the
     * mini calendar on the home screen has real days to colour in instead of
     * just today.
     */
    case 'settimana':
      return simula(7, () => 'pieno', doloreRealistico, adesso);

    /**
     * Thirty-nine full days. Phase one closes on schedule and phase two is
     * left exactly 22 RP short of its threshold — one full day's worth
     * (16 + 4 + 2, phase two still has the drug block) — so finishing today's
     * checklist and confirming the level-up crosses into phase three live.
     * `grafico-dolore` is already unlocked (phase >= 2); `calendario-heatmap`
     * (phase >= 3) is the one that unlocks on stage. Streak 34, x2.65, ~1427
     * gems — comfortably enough to redeem any reward in the catalogue,
     * including the phase-3-gated one, right after the level-up.
     */
    case 'presentazione':
      return simula(39, () => 'pieno', doloreRealistico, adesso);
  }
}
